[ERROR] java.lang.IllegalStateException: There is no context available for qualifier org.jboss.arquillian.drone.api.annotation.Default. Available contexts are [].
[ERROR] at org.jboss.arquillian.graphene.context.GrapheneContextImpl$LazyContext.getContext(GrapheneContextImpl.java:302)
[ERROR] at org.jboss.arquillian.graphene.context.GrapheneContextImpl$LazyContext.getConfiguration(GrapheneContextImpl.java:234)
[ERROR] at org.jboss.arquillian.graphene.DefaultGrapheneRuntime.waitGui(DefaultGrapheneRuntime.java:104)
[ERROR] at org.jboss.arquillian.graphene.Graphene.waitGui(Graphene.java:216)
[ERROR] at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:44)
[ERROR] at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
[ERROR] at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:209)
[ERROR] at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
[ERROR] at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:205)
[ERROR] at com.sun.proxy.$Proxy31.switchTo(Unknown Source)
[ERROR] at org.jboss.qa.brms.tools.GrapheneExtension.isAlertPresent(GrapheneExtension.java:740)
[ERROR] at org.jboss.qa.brms.tools.GrapheneExtension.dismissAlerts(GrapheneExtension.java:1502)
[ERROR] at org.jboss.qa.brms.tools.GrapheneTestListener.tryCaptureScreenshot(GrapheneTestListener.java:31)
[ERROR] at org.jboss.qa.brms.tools.GrapheneTestListener.onConfigurationFailure(GrapheneTestListener.java:27)
[ERROR] at org.testng.internal.Invoker.runConfigurationListeners(Invoker.java:1868)
[ERROR] at org.testng.internal.Invoker.handleConfigurationFailure(Invoker.java:334)
[ERROR] at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:237)
[ERROR] at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
[ERROR] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
[ERROR] at org.testng.SuiteRunner.run(SuiteRunner.java:240)
[ERROR] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[ERROR] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[ERROR] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
[ERROR] at org.testng.TestNG.run(TestNG.java:1057)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:69)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:181)
[ERROR] at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)